server:
  port: 8092
#  servlet:
#    context-path:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdemo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.wjf.demo.mybatisplus.entity
  mapper-locations: classpath:mybatis/mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
